kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: glusterfs-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "glusterfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
