apiVersion: v1
kind: Pod
metadata: 
  name: glusterfs-provisioner
spec: 
  containers: 
    - 
      env: 
        - 
          name: PROVISIONER_NAME
          value: gluster.org/glusterfs
      image: "quay.io/external_storage/glusterfile-provisioner:latest"
      name: glusterfs-provisioner
